services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    container_name: pcb_backend_engine
    volumes:
      - .:/app

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    container_name: pcb_frontend_ui
    ports:
      - "8050:8050"
    volumes:
      - .:/app
    depends_on:
      - backend    
